services:
  postgres:
    image: postgres:16
    container_name: fasoecole_postgres
    environment:
      POSTGRES_DB: fasoecoleBD
      POSTGRES_USER: fasoecole_bd_user
      POSTGRES_PASSWORD: fasoecole_bd_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: